### PR TITLE
into plist

### PR DESCRIPTION
**Pull request by crides**

### CODE REVIEW

**Comment by ayax79** [comment]
Thanks, everything should be up to date now.

**Comment by crides** [comment]
Hmmm? You closed this as completed without actually merging?

**Comment by ayax79** [comment]
No, as I had some other changes I wanted to do and I also wanted to push up to the most current nushell version, not 0.88. Sorry, for not seeing this early. I haven't been great at checking.

**Comment by crides** [comment]
> Sorry, for not seeing this early. I haven't been great at checking.

No problem.

What I was asking, is that you marked this PR as completed (and not declined), but I don't see a `to plist` command on latest `main`?

**Comment by ayax79** [comment]
I missed it. I reopened, manually merged the changes locally since there were quite a few conflicts and merged into main. Thanks for the contribution!

**Pull request closed without merging**
